# Based on GTSAM file (by @ProfFan)
name: CI Linux

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      fail-fast: false
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        name: [
          ubuntu-18.04-gcc,
          ubuntu-latest-clang,
          ubuntu-latest-gcc
        ]

        build_type: [ Release ]
        include:
          - name: ubuntu-18.04-gcc
            os: ubuntu-18.04
            compiler: gcc
            coverage: OFF

          - name: ubuntu-latest-clang
            os: ubuntu-latest
            compiler: clang
            coverage: OFF

          - name: ubuntu-latest-gcc
            os: ubuntu-latest
            compiler: gcc
            coverage: ON

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade

          sudo apt install cmake build-essential cmake libwxgtk3.0-gtk3-dev \
                           libopencv-dev libeigen3-dev libgtest-dev \
                           freeglut3-dev libglfw3-dev libassimp-dev \
                           libglu1-mesa-dev libqt5opengl5-dev qtbase5-dev \
                           libxrandr-dev libxxf86vm-dev \
                           libftdi-dev libusb-1.0-0-dev libudev-dev libfreenect-dev \
                           libdc1394-22-dev libavformat-dev libswscale-dev libpcap-dev \
                           liboctomap-dev libopenni2-dev \
                           libtinyxml2-dev \
                           yamllint

          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt install libicu-dev libsimpleini-dev
          fi

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++ g++
            echo "::set-env name=CC::gcc"
            echo "::set-env name=CXX::g++"
          else
            sudo apt-get install -y clang g++-multilib
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
          fi
      - name: Git submodule (Linux)
        run: |
          git submodule sync
          git submodule update --init --recursive
      - name: CMake configure (Linux)
        run: |
          cmake -DMRPT_BUILD_EXAMPLES=On \
                -DMRPT_BUILD_TESTING=On \
                -DMRPT_ENABLE_COVERAGE="${{ matrix.coverage }}" \
                -DMRPT_ALLOW_LGPLV3=ON \
                -DCMAKE_VERBOSE_MAKEFILE=ON \
                -H. -Bbuild
      - name: Build (Linux)
        run: |
          make -C build tests_build_all
          make CTEST_OUTPUT_ON_FAILURE=1 test -C build
          if [ "${{ matrix.coverage }}" = "ON" ]; then
            make gcov -C build
            bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build
          fi
          make -C build
